SoftverZaHladnjacu.Client/Controllers/HladnjacaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using SoftverZaHladnjacu.Domain;
using SoftverZaHladnjacu.Domain.Repository;
using SoftverZaHladnjacu.EntityFramework;

namespace SoftverZaHladnjacu.Client.Controllers
{
    [Authorize(Roles = "Manager")]
    public class HladnjacaController : Controller
    {
        private IHladnjacaRepository _hladnjacaRepository;
        public HladnjacaController()
        {
            _hladnjacaRepository = new HladnjacaRepository();
        }

        // GET: Hladnjaca
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllHladnjacas()
        {
            return PartialView("Hladnjace", _hladnjacaRepository.GetAll());
        }

        public ActionResult Create()
        {
            ViewBag.Tipovi = _hladnjacaRepository.GetAllTypes();
            return View();
        }

        [HttpPost]
        public ActionResult Create(HladnjacaBO hladnjacaBO)
        {
            if(_hladnjacaRepository.Create(hladnjacaBO) > 0)
            {
                return Content("<script> alert('Hladnjača je kreirana'); window.location = '/Hladnjaca/Create' </script>");
            }
            else
            {
                ViewBag.Tipovi = _hladnjacaRepository.GetAllTypes();
                ViewBag.MessageF = "Došlo je do greške, hladnjača nije kreirana!";
                return View(hladnjacaBO);
            }
        }

        public ActionResult Edit(int id)
        {
            HladnjacaBO hladnjacaBO = _hladnjacaRepository.GetById(id);
            return View(hladnjacaBO);
        }

        [HttpPost]
        public ActionResult Edit(HladnjacaBO hladnjacaBO)
        {
            if(_hladnjacaRepository.Update(hladnjacaBO) > 0)
            {
                ViewBag.MessageS = "Hladnjača je ažurirana";
                return View("Index");
            }
            else
            {
                ViewBag.MessageF = "Došlo je do greške, hladnjača nije ažurirana!";
                return View(hladnjacaBO);
            }
        }
    }
}

SoftverZaHladnjacu.Client/Controllers/OtpremnicaController.cs
using SoftverZaHladnjacu.Domain;
using SoftverZaHladnjacu.Domain.Repository;
using SoftverZaHladnjacu.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftverZaHladnjacu.Client.Controllers
{
    [Authorize]
    public class OtpremnicaController : Controller
    {
        private IOtpremnicaRepository _otpremnicaRepository;
        private IPoslovniPartnerRepository _poslovniPartnerRepository;
        private IPakovanjeRepository _pakovanjeRepository;
        public OtpremnicaController()
        {
            _otpremnicaRepository = new OtpremnicaRepository();
            _poslovniPartnerRepository = new PoslovniPartnerRepository();
            _pakovanjeRepository = new PakovanjeRepository();
        }
        // GET: Otpremnica
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllOtpremnicas()
        {
            return PartialView("Otpremnice", _otpremnicaRepository.GetAll());
        }

        public ActionResult GetOtpremnicasById(int id)
        {
            return PartialView("Otpremnice", _otpremnicaRepository.GetListById(id));
        }

        public ActionResult Create()
        {
            ViewBag.Kupci = _poslovniPartnerRepository.GetKupci();
            return View();
        }

        [HttpPost]
        public ActionResult Create(OtpremnicaBO otpremnicaBO)
        {
            var postedValues = Request.Form.GetValues("pakovanje");
            List<int> listaSifri = new List<int>();
            ViewBag.Kupci = _poslovniPartnerRepository.GetKupci();
            foreach (string value in postedValues)
            {
                if(value != null && value != "")
                {
                    try
                    {
                        int sifra = Convert.ToInt32(value);
                        listaSifri.Add(sifra);
                    }
                    catch (Exception)
                    {
                        ViewBag.MessageF = "Došlo je do greške, uneta je pogrešna šifra pakovanja!";
                        return View();
                    }
                }
            }
            if(listaSifri.Count <= 0)
            {
                ViewBag.MessageF = "Morate uneti stavke otpremnice!";
                return View();
            }
            otpremnicaBO.ListaSifri = listaSifri;
            int created = _otpremnicaRepository.Create(otpremnicaBO);
            if (created > 0)
            {
                ViewBag.MessageS = "Otpremnica je kreirana";
                return View("Index");
            } else
            {
                ViewBag.MessageF = "Došlo je do greške, otpremnica nije kreirana!";
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            OtpremnicaBO otpremnicaBO = _otpremnicaRepository.GetById(id);
            return View(otpremnicaBO);
        }


        public ActionResult Edit(int id)
        {
            if (_otpremnicaRepository.Update(id) > 0)
            {
                ViewBag.MessageS = "Otpremnica je stornirana";
                return View("Index");
            }
            else
            {
                ViewBag.MessageF = "Došlo je do greške, otpremnica nije stornirana!";
                return View("Index");
            }
        }
    }
}

SoftverZaHladnjacu.Client/Controllers/PakovanjeController.cs
using SoftverZaHladnjacu.Domain;
using SoftverZaHladnjacu.Domain.Repository;
using SoftverZaHladnjacu.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftverZaHladnjacu.Client.Controllers
{
    [Authorize]
    public class PakovanjeController : Controller
    {
        private IPakovanjeRepository _pakovanjeRepository;
        private IHladnjacaRepository _hladnjacaRepository;
        private IPrijemnicaRepository _prijemnicaRepository;
        private ISortaRepository _sortaRepository;
        public PakovanjeController()
        {
            _pakovanjeRepository = new PakovanjeRepository();
            _hladnjacaRepository = new HladnjacaRepository();
            _prijemnicaRepository = new PrijemnicaRepository();
            _sortaRepository = new SortaRepository();
        }
        // GET: Pakovanje
        public ActionResult Index()
        {
            ViewBag.Hladnjace = _hladnjacaRepository.GetAllTypeGlavna();
            ViewBag.Klase = _pakovanjeRepository.GetAllKlasa();
            ViewBag.Sorte = _sortaRepository.GetAll();
            return View();
        }

        public int CheckId(int id)
        {
            PakovanjeBO pakovanje = _pakovanjeRepository.GetById(id);
            if(pakovanje != null && pakovanje.Id > 0 && pakovanje.DatumIzdavanja == null)
            {
                return 1;
            }
            return 0;
        }

        public ActionResult GetPakovanja()
        {
            return PartialView("Pakovanja", _pakovanjeRepository.GetAll());
        }

        public ActionResult GetPakovanjaByHladnjaca(int id)
        {
            return PartialView("Pakovanja", _pakovanjeRepository.GetPakovanjaByHladnjaca(id));
        }

        public ActionResult GetPakovanjaByKlasa(int id)
        {
            return PartialView("Pakovanja", _pakovanjeRepository.GetPakovanjaByKlasa(id));
        }
        public ActionResult GetPakovanjaBySorta(int id)
        {
            return PartialView("Pakovanja", _pakovanjeRepository.GetPakovanjaBySorta(id));
        }


        public ActionResult Create(int id)
        {
            ViewBag.Prijemnica = _prijemnicaRepository.GetById(id);
            ViewBag.Klase = _pakovanjeRepository.GetAllKlasa();
            ViewBag.Hladnjace = _hladnjacaRepository.GetAllTypeGlavna();
            return View();
        }

        [HttpPost]
        public ActionResult Create(PakovanjeBO pakovanjeBO)
        {
            HladnjacaBO hladnjacaBO = _hladnjacaRepository.GetById(pakovanjeBO.Hladnjaca.Id);
            PrijemnicaBO prijemnicaBO = _prijemnicaRepository.GetById(pakovanjeBO.Id);
            ViewBag.Klase = _pakovanjeRepository.GetAllKlasa();
            ViewBag.Hladnjace = _hladnjacaRepository.GetAllTypeGlavna();
            ViewBag.Prijemnica = prijemnicaBO;
            if (prijemnicaBO.SkladisniKalo < pakovanjeBO.Kolicina)
            {
                ModelState.AddModelError("Kolicina", "Količina za pakovanje mora biti manja od količine u hladnjači.");
                return View();
            }
            if (hladnjacaBO.Kapacitet < pakovanjeBO.Kolicina)
            {
                ModelState.AddModelError("Hladnjaca.Id", "Kapacitet odabrane hladnjače mora biti veći od unete količine.");
                return View();
            }
            int created = _pakovanjeRepository.Create(pakovanjeBO);
            if (created > 0)
            {
                ViewBag.MessageS = "Pakovanje je kreirano";
                List<HladnjacaBO> listaHladnjaca = (List<HladnjacaBO>)_hladnjacaRepository.GetAllTypeGlavna();
                foreach(HladnjacaBO hladnjaca in listaHladnjaca)
                {
                    if(hladnjaca.Id == hladnjacaBO.Id)
                    {
                        hladnjaca.Kapacitet -= pakovanjeBO.Kolicina;
                    }
                }
                prijemnicaBO.SkladisniKalo -= pakovanjeBO.Kolicina;
                ViewBag.Hladnjace = listaHladnjaca;
                ViewBag.Prijemnica = prijemnicaBO;
                return View();
            }
            else
            {
                ViewBag.MessageF = "Došlo je do greške, pakovanje nije kreirano";
                return View();
            }
        }

    }
}

SoftverZaHladnjacu.Client/Controllers/PrijemnicaController.cs
using SoftverZaHladnjacu.Domain;
using SoftverZaHladnjacu.Domain.Repository;
using SoftverZaHladnjacu.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftverZaHladnjacu.Client.Controllers
{
    [Authorize]
    public class PrijemnicaController : Controller
    {
        private IPrijemnicaRepository _prijemnicaRepository;
        private IPoslovniPartnerRepository _poslovniPartnerRepository;
        private ISortaRepository _sortaRepository;
        private IHladnjacaRepository _hladnjacaRepository;
        private IPakovanjeRepository _pakovanjeRepository;
        public PrijemnicaController()
        {
            _prijemnicaRepository = new PrijemnicaRepository();
            _poslovniPartnerRepository = new PoslovniPartnerRepository();
            _sortaRepository = new SortaRepository();
            _hladnjacaRepository = new HladnjacaRepository();
            _pakovanjeRepository = new PakovanjeRepository();
        }

        // GET: Prijemnica
        public ActionResult Index()
        {
            ViewBag.Sorte = _sortaRepository.GetAll();
            return View();
        }

        public ActionResult GetPrijemnicasById(int id)
        {
            return PartialView("Prijemnice", _prijemnicaRepository.GetListById(id));
        }

        public ActionResult GetPrijemnicasByDate(DateTime date)
        {
            return PartialView("Prijemnice", _prijemnicaRepository.GetByDate(date));
        }

        public ActionResult GetPrijemnicasBySorta(int id)
        {
            return PartialView("Prijemnice", _prijemnicaRepository.GetBySorta(id));
        }

        public ActionResult GetPrijemnicasToBeStored()
        {
            return PartialView("Prijemnice", _prijemnicaRepository.GetAllNotStored());
        }

        public ActionResult GetAvailableCapacity()
        {
            return PartialView("Kapaciteti", _hladnjacaRepository.GetAllTypeGlavna());
        }

        public ActionResult Create()
        {
            ViewBag.Dobavljaci = _poslovniPartnerRepository.GetDobavljaci();
            ViewBag.Hladnjace = _hladnjacaRepository.GetAllTypePrijemna();
            ViewBag.Sorte = _sortaRepository.GetAll();

            return View();
        }

        [HttpPost]
        public ActionResult Create(PrijemnicaBO prijemnicaBO)
        {
            HladnjacaBO hladnjacaBO = _hladnjacaRepository.GetById(prijemnicaBO.Hladnjaca.Id);
            ViewBag.Dobavljaci = _poslovniPartnerRepository.GetDobavljaci();
            ViewBag.Hladnjace = _hladnjacaRepository.GetAllTypePrijemna();
            ViewBag.Sorte = _sortaRepository.GetAll();
            if (hladnjacaBO.Kapacitet < prijemnicaBO.Kolicina)
            {
                ModelState.AddModelError("Hladnjaca.Id", "Kapacitet odabrane hladnjače manji je od unete količine.");
                return View(prijemnicaBO);
            }
            if (_prijemnicaRepository.Create(prijemnicaBO) > 0)
            {
                ViewBag.MessageS = "Prijemnica je kreirana";
                return View("Index");
            } 
            else
            {
                ViewBag.MessageF = "Došlo je do greške, prijemnica nije kreirana!";
                return View(prijemnicaBO);
            }
        }

        public ActionResult Edit(int id)
        {
            if (_prijemnicaRepository.UpdateSetStored(id) > 0)
            {
                ViewBag.Sorte = _sortaRepository.GetAll();
                ViewBag.MessageS = "Prijemnica je ažurirana";
                return View("Index");
            }
            else
            {
                ViewBag.MessageF = "Došlo je do greške, prijemnica nije ažurirana!";
                return View("Index");
            }
        }
    }
}

SoftverZaHladnjacu.Client/Views/Shared/Hladnjace.cshtml
@model IEnumerable<SoftverZaHladnjacu.Domain.HladnjacaBO>

<p>
    @Html.ActionLink("Kreiraj novu", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kapacitet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aktivna)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipHladnjace.Naziv) Tipa
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Kapacitet)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Aktivna)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TipHladnjace.Naziv)
    </td>
    <td>
        @Html.ActionLink("Izmeni", "Edit", new { id = item.Id })
    </td>
</tr>
}

</table>

SoftverZaHladnjacu.Client/Views/Shared/Otpremnice.cshtml
@model IEnumerable<SoftverZaHladnjacu.Domain.OtpremnicaBO>

<p>
    @Html.ActionLink("Kreiraj novu", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PoslovniPartner.Naziv) kupca
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserBO.Ime) radnika
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumStorniranja)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Datum)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PoslovniPartner.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserBO.Ime) @Html.DisplayFor(modelItem => item.UserBO.Prezime)
    </td>
    <td>
        @if (item.DatumStorniranja == null)
            {
                @Html.ActionLink("Storniraj", "Edit", new { id = item.Id })
            }
            else
            {
                @Html.DisplayFor(modelItem => item.DatumStorniranja)
            }
    </td>
    <td>
        @Html.ActionLink("Detalji", "Details", new {id = item.Id})
    </td>
</tr>
}

</table>

SoftverZaHladnjacu.Client/Views/Shared/Pakovanja.cshtml
@model IEnumerable<SoftverZaHladnjacu.Domain.PakovanjeBO>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hladnjaca.Naziv) hladnjače
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kolicina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prijemnica.Sorta.Naziv) sorte
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Klasa.Naziv) klase
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prijemnica.Id) prijemnice
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumPakovanja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserBO.Ime) radnika
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumIzdavanja)
        </th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hladnjaca.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Kolicina)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Prijemnica.Sorta.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Klasa.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Prijemnica.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DatumPakovanja)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserBO.Ime) @Html.DisplayFor(modelItem => item.UserBO.Prezime)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DatumIzdavanja)
    </td>
</tr>
}

</table>

SoftverZaHladnjacu.Client/Views/Shared/Prijemnice.cshtml
@model IEnumerable<SoftverZaHladnjacu.Domain.PrijemnicaBO>

<p>
    @Html.ActionLink("Kreiraj novu", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumPrijema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hladnjaca.Naziv) hladnjače
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kolicina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sorta.Naziv) sorte
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PoslovniPartner.Naziv) poslovnog partnera
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumPakovanja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SkladisniKalo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserBO.Ime) radnika
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DatumPrijema)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hladnjaca.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Kolicina)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Sorta.Naziv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PoslovniPartner.Naziv) - @Html.DisplayFor(modelItem => item.PoslovniPartner.Adresa)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DatumPakovanja)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SkladisniKalo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserBO.Ime) @Html.DisplayFor(modelItem => item.UserBO.Prezime)
    </td>
    <td>
        @if (item.DatumPakovanja == null)
        {
            @Html.ActionLink("Skladišti", "../Pakovanje/Create", new { id = item.Id })
        }
    </td>
</tr>
}

</table>

SoftverZaHladnjacu.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        footer {
            position: fixed;
            left: 2rem;
            right: 2rem;
            bottom: 0;
            text-align: right;
            background-color: #fff;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Početna strana", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Prijem voća</a>
                            <div class="dropdown-menu">
                                <ul class="nav">
                                    <li>@Html.ActionLink("Nova prijemnica", "Create", "Prijemnica")</li>
                                    <li>@Html.ActionLink("Pretraga i skladištenje", "Index", "Prijemnica")</li>
                                </ul>
                            </div>
                        </li>
                        <li>@Html.ActionLink("Pretraga pakovanja", "Index", "Pakovanje")</li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Izdavanje voća</a>
                            <div class="dropdown-menu">
                                <ul class="nav">
                                    <li>@Html.ActionLink("Nova otpremnica", "Create", "Otpremnica")</li>
                                    <li>@Html.ActionLink("Rad sa otpremnicama", "Index", "Otpremnica")</li>
                                </ul>
                            </div>
                        </li>
                        if (User.IsInRole("Manager"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Rad sa hladnjačama</a>
                                <div class="dropdown-menu">
                                    <ul class="nav">
                                        <li>@Html.ActionLink("Dodaj novu hladnjaču", "Create", "Hladnjaca")</li>
                                        <li>@Html.ActionLink("Izmeni postojeću hladnjaču", "Index", "Hladnjaca")</li>
                                    </ul>
                                </div>
                            </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div class="col-md-12" style="height: 100px;"></div>
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - Marijana Banduka</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>